# Rust-错误处理

Rust 将错误分为两大类：可恢复的（recoverable）和 不可恢复的（unrecoverable）错误。对于一个可恢复的错误，比如文件未找到的错误，我们很可能只想向用户报告问题并重试操作。

## 1 不可恢复错误

手动抛出panic。

```rust
fn main() {
    //宏实现panic
    panic!("crash and burn");
}
```

为了保护程序远离类似缓冲区溢出的漏洞，如果尝试读取一个索引不存在的元素，Rust 会停止执行并拒绝继续。

```rust
fn main() {
    let v = vec![1, 2, 3];

    v[99];//panic whe cargo run
}
```

当设置 RUST_BACKTRACE 环境变量时 panic! 调用所生成的 backtrace 信息。当出现 panic 时，程序默认会开始 展开（unwinding），这意味着 Rust 会回溯栈并清理它遇到的每一个函数的数据，不过这个回溯并清理的过程有很多工作。另一种选择是直接 终止（abort），这会不清理数据就退出程序。那么程序所使用的内存需要由操作系统来清理。如果你需要项目的最终二进制文件越小越好，panic 时通过在 Cargo.toml 的 [profile] 部分增加 panic = 'abort'，可以由展开切换为终止。例如，如果你想要在 release 模式中 panic 时直接终止：

```toml
[profile.release]
panic = 'abort'
```

## 2 可恢复错误

Result<T, E> 类型，用于处理可恢复的错误。T 和 E 是泛型类型参数。

在 Rust 中，ERR() 和 Ok() 并不是枚举类型的一部分，而是标准库中某些特定枚举的成员。Ok() 是 Result<T, E> 枚举的一个成员。Result<T, E> 枚举用于包含一个操作可能成功（返回结果）或者失败（返回错误）的情况。它有两个成员：Ok(T) 表示操作成功，并带有结果 T；Err(E) 表示操作失败，并带有错误 E。


```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
使用 match 表达式处理可能会返回的 Result 成员。

```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
}
```
返回Result并且需要在失败时 panic，可以采用简写模式：unwrap 和 expect。

```rust
    let greeting_file = File::open("hello.txt").unwrap();

    let greeting_file = File::open("hello.txt")
        .expect("hello.txt should be included in this project");
```

传播错误。**Result 值之后的 ? 被定义为与处理 Result 值的 match 表达式有着完全相同的工作方式。** 如果 Result 的值是 Ok，这个表达式将会返回 Ok 中的值而程序将继续执行。如果值是 Err，Err 中的值将作为整个函数的返回值，就好像使用了 return 关键字一样，这样错误值就被传播给了调用者。? 运算符消除了大量样板代码并使得函数的实现更简单。我们甚至可以在 ? 之后直接使用链式方法调用来进一步缩短代码。

注意，? 运算符只能被用于返回值与 ? 作用的值相兼容的函数。例如作用于Result或Option,则函数返回值也是对应的Result和Option。

```rust
//一般写法
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}

//使用?实现简短模式写法
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}

//?的链式写法
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();

    File::open("hello.txt")?.read_to_string(&mut username)?;

    Ok(username)
}
```

